post_install() {
	echo '--> On first run, use 'clight -s' to create your user config file.'
	echo '--> Running setup is not mandatory. By default, first matching webcam and backlight interface are used.'
	echo '--> Therefore, it should work out of the box even without setup on most cases.'
	echo '--> Then, remember to enable the unit file shipped (without sudo): systemctl --user enable clight.service'
	echo '--> Finally, reboot the system.
}

