post_install() {
    echo '--> By default, first matching webcam and backlight interface are used.'
	echo '--> Therefore, it should work out of the box even without any setup in most cases.'
	echo '--> Clight installs a xdg autostart script. This way, clight will be started together with your DE.'
	echo '--> For any customization, take a look at settings file placed in /etc/default/clight.conf.'
}

